# Use root/example as user/password credentials
version: '3.9'

services:

  mongo-service:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecorth
      MONGO_INITDB_ROOT_PASSWORD: ecorth
    networks:
     - ecorth
  mongo-express:
    image: mongo-express
    ports:
      - 9001:9001
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ecorth
      ME_CONFIG_MONGODB_ADMINPASSWORD: ecorth
      ME_CONFIG_MONGODB_URL: mongodb://ecorth:ecorth@mongo:27017/
    networks:
     - ecorth
networks:
 ecorth:
  name: ecorth
